development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack_api_url:   <%= ENV["SLACK_API_URL"] %>
  particle_api_key: <%= ENV["PARTICLE_API_KEY"] %>
  particle_device_id: <%= ENV["PARTICLE_DEVICE_ID"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack_api_url:   <%= ENV["SLACK_API_URL"] %>
  particle_api_key:    <%= ENV["PARTICLE_API_KEY"] %>
  particle_device_id:   <%= ENV["PARTICLE_DEVICE_ID"] %>
